// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    404: typeof import('./components/common/NotFound.vue')['default']
    Alert: typeof import('./components/common/alert.vue')['default']
    Chart: typeof import('./components/chart/index.vue')['default']
    copy: typeof import('././components/common/Popup/index.vuenCascader.vue')['default']
    CountTo: typeof import('./components/common/CountTo.vue')['default']
    DarkModeSwitch: typeof import('./components/common/DarkModeSwitch.vue')['default']
    Hr: typeof import('./components/common/Hr-horizontal.vue')['default']
    IconMdiBellOutline: typeof import('~icons/mdi/bell-outline')['default']
    IconMdiBrightness2: typeof import('~icons/mdi/brightness2')['default']
    IconMdiBrightness4: typeof import('~icons/mdi/brightness4')['default']
    'IconMdiChevron-': typeof import('~icons/mdi/chevron-')['default']
    IconMdiChevronDown: typeof import('~icons/mdi/chevron-down')['default']
    IconMdiChevronUp: typeof import('~icons/mdi/chevron-up')['default']
    IconMdiClose: typeof import('~icons/mdi/close')['default']
    IconMdiCog: typeof import('~icons/mdi/cog')['default']
    IconMdiFilterVariant: typeof import('~icons/mdi/filter-variant')['default']
    IconMdiMenu: typeof import('~icons/mdi/menu')['default']
    IconMdiMenuClose: typeof import('~icons/mdi/menu-close')['default']
    IconMdiMoonWaningCrescent: typeof import('~icons/mdi/moon-waning-crescent')['default']
    IconMdiPin: typeof import('~icons/mdi/pin')['default']
    IconMdiPinOff: typeof import('~icons/mdi/pin-off')['default']
    IconMdiWhiteBalanceSunny: typeof import('~icons/mdi/white-balance-sunny')['default']
    Message: typeof import('./components/common/Message.vue')['default']
    NCascader: typeof import('naive-ui')['NCascader']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NotFound: typeof import('./components/common/NotFound.vue')['default']
    NTreeSelect: typeof import('naive-ui')['NTreeSelect']
    OrganizationCascader: typeof import('./components/common/OrganizationCascader.vue')['default']
    OrganizationFilter: typeof import('./components/common/OrganizationFilter.vue')['default']
    OrganizationSelect: typeof import('./components/common/OrganizationCascader.vue')['default']
    Overlay: typeof import('./components/common/Overlay.vue')['default']
    Popup: typeof import('./components/common/Popup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tab: typeof import('./components/common/Tab.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCascader: typeof import('vant/es')['Cascader']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCol: typeof import('vant/es')['Col']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanIcon: typeof import('vant/es')['Icon']
    VanPopup: typeof import('vant/es')['Popup']
    VanRow: typeof import('vant/es')['Row']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
  }
}
