// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Chart: typeof import('./components/chart/index.vue')['default']
    copy: typeof import('./components/common/OrganizationSelect.vue')['default']
    CountTo: typeof import('./components/common/CountTo.vue')['default']
    DarkModeSwitch: typeof import('./components/common/DarkModeSwitch.vue')['default']
    IconMdiFilterVariant: typeof import('~icons/mdi/filter-variant')['default']
    IconMdiMoonWaningCrescent: typeof import('~icons/mdi/moon-waning-crescent')['default']
    IconMdiWhiteBalanceSunny: typeof import('~icons/mdi/white-balance-sunny')['default']
    Message: typeof import('./components/common/Message.vue')['default']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NTreeSelect: typeof import('naive-ui')['NTreeSelect']
    OrganizationFilter: typeof import('./components/common/OrganizationFilter.vue')['default']
    OrganizationSelect: typeof import('./components/common/OrganizationSelect.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCol: typeof import('vant/es')['Col']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanRow: typeof import('vant/es')['Row']
  }
}
